
#--------------------------------------------------------------------------
# File and Version Information:
#      $Id: GNUmakefile,v 1.3 2002/10/31 14:56:45 hejny Exp $
#
# Description:
# 	GNUmakefile template for the package building 
#	for PANDA software
#
# Environment:
#      Software developed for the PANDA Detector at GSI, Darmstadt
#
# Author List:
#      Sergey Ganzhur                Original Author
#
# Copyright Information:
#      Copyright (C) 2002           Ruhr Universitaet Bochum
#
#------------------------------------------------------------------------

#################################################################
# Package name

PACKAGE = DpmEvtGen

#################################################################
#++ binary products                             [build it with 'bin'] 

MAIN    = main
PROGRAM = DPMGen

 
#################################################################
#++ include standard makefile
include standard_FORTRAN.mk


